//! Strict CBOR (RFC 8949) runtime for codecs generated by cddl-zig.
//!
//! Decoding accepts any well-formed, valid encoding unless
//! `DecodeOptions.require_deterministic` is set; encoding always produces core
//! deterministic encoding (RFC 8949 Section 4.2.1).

const std = @import("std");

/// Runtime ABI implemented by this module; generated codecs check it at compile time.
pub const abi_version: u32 = 1;

const errors = @import("errors.zig");
pub const MalformedError = errors.MalformedError;
pub const InvalidError = errors.InvalidError;
pub const NonDeterministicError = errors.NonDeterministicError;
pub const SchemaError = errors.SchemaError;
pub const LimitError = errors.LimitError;
pub const AllocationError = errors.AllocationError;
pub const OutputError = errors.OutputError;
pub const DecodeError = errors.DecodeError;
pub const EncodeError = errors.EncodeError;
pub const Error = errors.Error;
pub const ErrorKind = errors.ErrorKind;
pub const errorKind = errors.errorKind;

const head = @import("head.zig");
pub const Major = head.Major;
pub const Head = head.Head;

const float = @import("float.zig");
pub const FloatWidth = float.Width;

const decoder = @import("decoder.zig");
pub const Limits = decoder.Limits;
pub const DecodeOptions = decoder.DecodeOptions;
pub const Decoder = decoder.Decoder;
pub const Kind = decoder.Kind;
pub const Float = decoder.Float;
pub const Span = decoder.Span;
pub const StringRef = decoder.StringRef;
pub const Array = decoder.Array;
pub const Map = decoder.Map;
pub const MapKey = decoder.MapKey;
pub const Checkpoint = decoder.Checkpoint;
pub const decodeValue = decoder.decodeValue;
pub const validate = decoder.validate;

const encoder = @import("encoder.zig");
pub const Encoder = encoder.Encoder;
pub const MapBuilder = encoder.MapBuilder;
pub const ValueMode = encoder.ValueMode;
pub const encodeValueAlloc = encoder.encodeValueAlloc;

pub const Value = @import("value.zig").Value;

/// Runtime source files, for vendoring next to generated code.
pub const embed = @import("embed.zig");

test {
    _ = errors;
    _ = head;
    _ = float;
    _ = @import("canonical.zig");
    _ = @import("value.zig");
    _ = decoder;
    _ = encoder;
    _ = embed;
}

test "decode, inspect, and re-encode through the public API" {
    const gpa = std.testing.allocator;
    const input = [_]u8{ 0xa2, 0x61, 'f', 0xfb, 0x3f, 0xf8, 0, 0, 0, 0, 0, 0, 0x61, 'n', 0x18, 0x2a };
    var d = Decoder.init(gpa, &input, .{});
    var m = try d.beginMap();
    defer m.deinit(&d);
    var n: ?u64 = null;
    var f: ?f64 = null;
    while (try d.nextMapKey(&m)) |key| {
        if (key.isText("n")) {
            n = try d.readUint();
        } else if (key.isText("f")) {
            f = try d.readFloat();
        } else {
            return error.UnexpectedMapKey;
        }
    }
    try d.endMap(&m);
    try d.finish();

    var buf: [16]u8 = undefined;
    var e = Encoder.initFixed(&buf);
    try e.writeMapHeader(2);
    try e.writeText("f");
    try e.writeFloat(f.?);
    try e.writeText("n");
    try e.writeUint(n.?);
    try std.testing.expectEqualSlices(u8, &.{ 0xa2, 0x61, 'f', 0xf9, 0x3e, 0x00, 0x61, 'n', 0x18, 0x2a }, buf[0..e.len]);
    try validate(gpa, buf[0..e.len], .{ .require_deterministic = true });
    try std.testing.expectError(error.NonPreferredFloat, validate(gpa, &input, .{ .require_deterministic = true }));
    try std.testing.expectEqual(ErrorKind.nondeterministic, errorKind(error.NonPreferredFloat));
}
