const std = @import("std");
const model = @import("model.zig");
const planning = @import("plan.zig");

pub const Error = planning.Error || error{ InvalidRuntimeImport, InvalidGeneratedSource };
pub const Options = struct {
    runtime_import: []const u8 = "cddl_runtime",
    header: bool = true,
    /// Set on a planning error; spans are available through Model.node(id).origin.
    failed_node: ?*?model.NodeId = null,
};

/// Returns ASCII Zig source owned by allocator. No source or model storage is borrowed.
pub fn generate(allocator: std.mem.Allocator, source: *const model.Model, options: Options) Error![]u8 {
    if (options.runtime_import.len == 0 or std.mem.indexOfScalar(u8, options.runtime_import, 0) != null) return error.InvalidRuntimeImport;
    var plan = try planning.build(allocator, source, options.failed_node);
    defer plan.deinit();
    var emitter = Emitter{ .allocator = allocator, .plan = &plan };
    errdefer emitter.output.deinit(allocator);
    if (options.header) try emitter.add("// Generated by cddl-zig. Decode results own their nested storage.\n");
    try emitter.add("const __cddl_std = @import(\"std\");\nconst __cddl_rt = @import(");
    try emitter.string(options.runtime_import);
    try emitter.add(");\n\ncomptime {\n    if (__cddl_rt.abi_version != 1) @compileError(\"incompatible cddl_runtime ABI\");\n}\n\n");
    for (plan.exports) |exported| {
        try emitter.print("pub const {s} = __cddl_T{d};\npub const {s} = __cddl_Codec({d});\n\n", .{ exported.name, exported.node, exported.codec_name, exported.node });
    }
    for (source.nodes, 0..) |node, id| {
        if (!plan.reachable[id]) continue;
        try emitter.print("const __cddl_T{d} = ", .{id});
        try emitter.typeExpression(@intCast(id), node);
        try emitter.add(";\n\n");
    }
    try emitter.add("fn __cddl_Type(comptime id: usize) type {\n    return switch (id) {\n");
    for (plan.reachable, 0..) |reachable, id| {
        if (reachable) try emitter.print("        {d} => __cddl_T{d},\n", .{ id, id });
    }
    try emitter.add("        else => unreachable,\n    };\n}\n\nconst __cddl_nodes = [_]__cddl_Node{\n");
    for (source.nodes, 0..) |node, id| {
        try emitter.add("    ");
        if (plan.reachable[id]) try emitter.nodeExpression(@intCast(id), node) else try emitter.add(".never");
        try emitter.add(",\n");
    }
    try emitter.add("};\n\n");
    try emitter.add(@embedFile("template.zig"));
    const text = try emitter.output.toOwnedSliceSentinel(allocator, 0);
    defer allocator.free(text);
    var tree = try std.zig.Ast.parse(allocator, text, .zig);
    defer tree.deinit(allocator);
    if (tree.errors.len != 0) return error.InvalidGeneratedSource;
    return tree.renderAlloc(allocator);
}

const Emitter = struct {
    allocator: std.mem.Allocator,
    plan: *const planning.Plan,
    output: std.ArrayList(u8) = .empty,

    fn add(self: *Emitter, text: []const u8) Error!void {
        try self.output.appendSlice(self.allocator, text);
    }

    fn print(self: *Emitter, comptime format: []const u8, arguments: anytype) Error!void {
        try self.output.print(self.allocator, format, arguments);
    }

    fn string(self: *Emitter, text: []const u8) Error!void {
        const hex = "0123456789abcdef";
        try self.add("\"");
        for (text) |byte| {
            switch (byte) {
                '"' => try self.add("\\\""),
                '\\' => try self.add("\\\\"),
                '\n' => try self.add("\\n"),
                '\r' => try self.add("\\r"),
                '\t' => try self.add("\\t"),
                0x20...0x21, 0x23...0x5b, 0x5d...0x7e => try self.output.append(self.allocator, byte),
                else => try self.add(&.{ '\\', 'x', hex[byte >> 4], hex[byte & 15] }),
            }
        }
        try self.add("\"");
    }

    fn number(self: *Emitter, value: model.Number) Error!void {
        switch (value) {
            .integer => |integer| try self.print(".{{ .integer = {d} }}", .{integer}),
            .float => |float| try self.print(".{{ .float = @bitCast(@as(u64, {d})) }}", .{@as(u64, @bitCast(float))}),
        }
    }

    fn literal(self: *Emitter, value: model.Literal) Error!void {
        switch (value) {
            .integer => |integer| try self.print(".{{ .integer = {d} }}", .{integer}),
            .float => |float| try self.print(".{{ .float = @bitCast(@as(u64, {d})) }}", .{@as(u64, @bitCast(float))}),
            .text, .bytes => |bytes| {
                try self.print(".{{ .{s} = ", .{@tagName(value)});
                try self.string(bytes);
                try self.add(" }");
            },
        }
    }

    fn optional(self: *Emitter, value: anytype) Error!void {
        if (value) |number_value| try self.print("{d}", .{number_value}) else try self.add("null");
    }

    fn typeExpression(self: *Emitter, id: model.NodeId, node: model.Node) Error!void {
        switch (node.data) {
            .reference => |child| try self.print("__cddl_T{d}", .{child}),
            .literal => |value| try self.add(switch (value) {
                .integer => "i65",
                .float => "f64",
                .bytes, .text => "[]const u8",
            }),
            .range => |range| try self.add(if (range.lower == .integer and range.upper == .integer) "i65" else "f64"),
            .control => |control| try self.print("__cddl_T{d}", .{control.target}),
            .choice => |children| {
                if (children.len == 0) return self.add("noreturn");
                if (children.len == 1) return self.print("__cddl_T{d}", .{children[0]});
                if (planning.scalar(self.plan.source, id)) |kind| return self.add(switch (kind) {
                    .integer => "i65",
                    .float => "f64",
                    .boolean => "bool",
                });
                try self.add("union(enum) {\n");
                for (children, 0..) |child, index| try self.print("    choice_{d}: __cddl_T{d},\n", .{ index, child });
                try self.add("}");
            },
            .array, .map => {
                try self.add("struct {\n");
                for (self.plan.fields[id]) |field| {
                    try self.print("    {s}: ", .{field.name});
                    if (field.occurrence.min == 1 and field.occurrence.max == 1) {
                        try self.print("__cddl_T{d}", .{field.value});
                    } else if (field.occurrence.max == 1) {
                        try self.print("?__cddl_T{d} = null", .{field.value});
                    } else {
                        try self.print("[]const __cddl_T{d}", .{field.value});
                        if (field.occurrence.min == 0) try self.add(" = &.{}");
                    }
                    try self.add(",\n");
                }
                try self.add("}");
            },
            .head => |head| switch (if (head.major) |major| @as(u4, major) else 8) {
                0 => try self.add("u64"),
                1 => try self.add("i65"),
                2, 3 => try self.add("[]const u8"),
                4 => try self.add("[]const __cddl_rt.Value"),
                5 => try self.add("[]const __cddl_rt.Value.Entry"),
                6 => {
                    try self.add("struct {\n    number: u64");
                    if (head.number) |number_value| try self.print(" = {d}", .{number_value});
                    try self.add(",\n    content: ");
                    if (head.content) |child| try self.print("__cddl_T{d}", .{child}) else try self.add("__cddl_rt.Value");
                    try self.add(",\n}");
                },
                7 => try self.add(if (head.number) |number_value| switch (number_value) {
                    20, 21 => "bool",
                    22, 23 => "void",
                    25...27 => "f64",
                    else => "u8",
                } else "struct { value: __cddl_rt.Value }"),
                else => try self.add("struct { value: __cddl_rt.Value }"),
            },
            else => return error.InvalidModel,
        }
    }

    fn nodeExpression(self: *Emitter, id: model.NodeId, node: model.Node) Error!void {
        switch (node.data) {
            .reference => |child| try self.print(".{{ .alias = {d} }}", .{child}),
            .literal => |value| {
                try self.add(".{ .literal = ");
                try self.literal(value);
                try self.add(" }");
            },
            .range => |range| {
                try self.add(".{ .range = .{ .lower = ");
                try self.number(range.lower);
                try self.add(", .upper = ");
                try self.number(range.upper);
                try self.print(", .inclusive = {} }} }}", .{range.inclusive});
            },
            .control => |control| {
                try self.print(".{{ .control = .{{ .operator = .{s}, .target = {d}, .controller = {d}, .size_max = ", .{ if (control.operator == .@"and") "@\"and\"" else @tagName(control.operator), control.target, control.controller });
                try self.optional(if (control.operator == .size) try planning.sizeMaximum(self.plan.source, control.controller) else @as(?u64, null));
                try self.add(" } }");
            },
            .choice => |children| {
                try self.add(".{ .choice = &.{");
                for (children, 0..) |child, index| {
                    if (index != 0) try self.add(",");
                    try self.print(" {d}", .{child});
                }
                if (children.len != 0) try self.add(" ");
                try self.add("} }");
            },
            .array, .map => {
                try self.print(".{{ .{s} = &.{{", .{@tagName(node.data)});
                const fields = self.plan.fields[id];
                if (fields.len != 0) try self.add("\n");
                for (fields) |field| {
                    try self.add("        .{ .name = ");
                    try self.string(field.name);
                    try self.print(", .value = {d}, .key = ", .{field.value});
                    try self.optional(field.key);
                    try self.print(", .min = {d}, .max = ", .{field.occurrence.min});
                    try self.optional(field.occurrence.max);
                    try self.add(" },\n");
                }
                try self.add(if (fields.len != 0) "    } }" else "} }");
            },
            .head => |head| {
                try self.add(".{ .head = .{ .major = ");
                try self.optional(head.major);
                try self.add(", .number = ");
                try self.optional(head.number);
                try self.add(", .number_type = ");
                try self.optional(head.number_type);
                try self.add(", .content = ");
                try self.optional(head.content);
                try self.add(" } }");
            },
            else => return error.InvalidModel,
        }
    }
};

test "generation owns deterministic output after planning" {
    const parser = @import("parser.zig");
    const semantic = @import("semantic.zig");
    const diagnostics = @import("diagnostics.zig");
    var messages = diagnostics.Diagnostics.init(std.testing.allocator);
    defer messages.deinit();
    var ast = try parser.parse(std.testing.allocator, .{ .name = "generation", .text = "packet = { id: uint, ? label: tstr, data: [* int] }" }, &messages);
    defer ast.deinit();
    var normalized = (try semantic.analyze(std.testing.allocator, &ast, &messages, .{})).?;
    defer normalized.deinit();
    const first = try generate(std.testing.allocator, &normalized, .{});
    defer std.testing.allocator.free(first);
    const second = try generate(std.testing.allocator, &normalized, .{});
    defer std.testing.allocator.free(second);
    try std.testing.expectEqualSlices(u8, first, second);
    const source = try std.testing.allocator.dupeZ(u8, first);
    defer std.testing.allocator.free(source);
    var syntax = try std.zig.Ast.parse(std.testing.allocator, source, .zig);
    defer syntax.deinit(std.testing.allocator);
    try std.testing.expectEqual(@as(usize, 0), syntax.errors.len);
}
